# Fichero de configuración para los contenedores del servidor de la aplicación CarShare
version: "3.8"

  # Crea un proxy inverso
  carshare-serverproxy:
    # Imagen base para generar el contenedor
    image: jwilder/nginx-proxy
    # Nombre asignado al contenedor
    container_name: carshare-serverproxy
    # Puertos abiertos para acceder al contenedor
    ports:
      - 81:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - carshare-server
    privileged: true

  rueda-db:
    # La imagen del contenedor se construye sobre una adecuando las necesidades
    image: mariadb:10.5.8
    # Nombre asignado al contenedor
    container_name: rueda-db
    # Red para el conjunto de contenedores
    ports:
        - 3306:3306
    #La ruta del volumen debe apuntar a la carpeta que contiene los datos de la base de datos
    volumes:
        - database:/var/lib/mysql
    #Variables de entorno  para el contenedor
    environment:
        - MYSQL_ROOT_PASSWORD=Chubaca2020
        - MYSQL_USER=rodrigo
        - MYSQL_PASSWORD=Chubaca2020
    networks:
      - carshare-server
    depends_on:
        - carshare-serverproxy

 # Contenedor para el servidor laravel
  carshare-server:
    # La imagen del contenedor se construye sobre una adecuando las necesidades
    build: .
    # Nombre asignado al contenedor
    container_name: carshare-server
    # Variable de entorno para el contendor
    environment:
      # Esta ruta debe estar incluida en el fichero hosts del anfitrión
      VIRTUAL_HOST: carshare.server.local
    depends_on:
        - carshare-db
        - carshare-serverproxy
    networks:
        - carshare-server
    # Se mapea la carpeta con una local
    volumes:
        - .:/var/www/html/
    depends_on:
        - rueda-db
        - serverproxy-rueda

networks:
    carshare-server:
        driver: bridge
volumes:
    database:
